import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { buildBlog } from './blog-build.mjs';

const root=process.cwd(), out=path.join(root,'dist');
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
const sourceHtml=fs.readFileSync(path.join(root,'index.html'),'utf8');
const appJs=fs.readFileSync(path.join(root,'app.js'),'utf8');
const match=appJs.match(/const translations = (\{[\s\S]*?\n\});\nconst config/);
if(!match) throw new Error('Could not read translations from app.js');
const translations=vm.runInNewContext(`(${match[1]})`);
const locales={
 sl:{prefix:'',hreflang:'sl',og:'sl_SI',title:'Zbiralnik prahu pri vrtanju | Vrtanje brez prahu',description:'Zbiralnik prahu za čistejše vrtanje v steno ali strop. Priklop na sesalno cev, manj čiščenja in obe roki prosti. Akcija 24,90 € → 14,90 €.',name:'Zbiralnik prahu pri vrtanju',short:'Lovilec prahu za vrtalnik, ki se priklopi na sesalno cev in prah prestreže tam, kjer nastane.'},
 en:{prefix:'/en',hreflang:'en',og:'en_US',title:'Drill Dust Collector | Dust-Free Drilling',description:'Drill dust collector for cleaner wall and ceiling drilling. Connect a vacuum hose, keep both hands free and reduce cleanup. Sale €24.90 → €14.90.',name:'Drill dust collector',short:'A compact drill dust catcher that connects to a vacuum hose and captures dust where drilling creates it.'},
 de:{prefix:'/de',hreflang:'de',og:'de_DE',title:'Bohrstaubfänger | Bohren ohne Staub',description:'Bohrstaubfänger für sauberes Bohren in Wand und Decke. Saugschlauch anschließen, beide Hände frei behalten und weniger putzen. Angebot 24,90 € → 14,90 €.',name:'Bohrstaubfänger',short:'Kompakter Staubfänger für die Bohrmaschine mit Anschluss an einen Saugschlauch.'},
 es:{prefix:'/es',hreflang:'es',og:'es_ES',title:'Colector de polvo para taladro | Taladrar sin polvo',description:'Colector de polvo para taladrar paredes y techos con menos suciedad. Conecta la manguera del aspirador y trabaja con las dos manos libres. Oferta 24,90 € → 14,90 €.',name:'Colector de polvo para taladro',short:'Recogedor de polvo compacto que se conecta a la manguera del aspirador y captura el polvo directamente.'}
};
function siteUrl(){const x=(process.env.SITE_URL||'').trim().replace(/\/$/,'');if(x)return x;const v=(process.env.VERCEL_PROJECT_PRODUCTION_URL||process.env.VERCEL_URL||'').trim().replace(/\/$/,'');return v?`https://${v}`:'http://localhost:3000'}
const base=siteUrl(),abs=p=>`${base}${p||'/'}`,esc=(s='')=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function replaceI18n(html,dict){for(const [key,value] of Object.entries(dict)){const re=new RegExp(`(<([a-z0-9]+)([^>]*data-i18n=["']${key}["'][^>]*)>)([\\s\\S]*?)(<\\/\\2>)`,'gi');html=html.replace(re,`$1${value}$5`)}return html}
function seoHead(lang){const l=locales[lang],pathname=l.prefix?`${l.prefix}/`:'/';const alts=Object.values(locales).map(x=>`<link rel="alternate" hreflang="${x.hreflang}" href="${abs(x.prefix?`${x.prefix}/`:'/')}" />`).join('\n  ');const ogAlts=Object.values(locales).filter(x=>x!==l).map(x=>`<meta property="og:locale:alternate" content="${x.og}" />`).join('\n  ');const faq=[1,2,3].map(i=>({'@type':'Question',name:translations[lang][`faq${i}Q`],acceptedAnswer:{'@type':'Answer',text:translations[lang][`faq${i}A`]}}));const ld={'@context':'https://schema.org','@graph':[{'@type':'Product','@id':`${abs(pathname)}#product`,name:l.name,image:[abs('/assets/product.webp')],description:l.short,offers:{'@type':'Offer',priceCurrency:'EUR',price:'14.90',url:abs(pathname),priceSpecification:{'@type':'UnitPriceSpecification',priceType:'https://schema.org/StrikethroughPrice',price:'24.90',priceCurrency:'EUR'}}},{'@type':'FAQPage','@id':`${abs(pathname)}#faq`,mainEntity:faq}]};return `<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1" /><link rel="canonical" href="${abs(pathname)}" />${alts}<link rel="alternate" hreflang="x-default" href="${abs('/')}" /><link rel="icon" href="/favicon.svg" type="image/svg+xml" /><link rel="manifest" href="/site.webmanifest" /><meta property="og:type" content="website" /><meta property="og:locale" content="${l.og}" />${ogAlts}<meta property="og:title" content="${esc(l.title)}" /><meta property="og:description" content="${esc(l.description)}" /><meta property="og:url" content="${abs(pathname)}" /><meta property="og:image" content="${abs('/assets/product.webp')}" /><meta property="og:image:alt" content="${esc(l.name)}" /><meta name="twitter:card" content="summary_large_image" /><meta name="twitter:title" content="${esc(l.title)}" /><meta name="twitter:description" content="${esc(l.description)}" /><meta name="twitter:image" content="${abs('/assets/product.webp')}" /><script type="application/ld+json">${JSON.stringify(ld)}</script>`}
function blogCards(){const c=[['Kako vrtati brez prahu: 7 praktičnih načinov','/blog/vrtanje-brez-prahu/'],['Lovilec prahu za vrtalnik: kako izbrati pravo rešitev','/blog/lovilec-prahu-za-vrtalnik/'],['Vrtanje v strop brez prahu','/blog/vrtanje-v-strop-brez-prahu/'],['Vrtanje v beton, opeko in knauf','/blog/vrtanje-beton-opeka-knauf/']];return `<section class="seo-guides section-pad"><div class="section-kicker">NASVETI</div><h2>Vrtanje brez prahu: vodiči in nasveti.</h2><div class="seo-guide-grid">${c.map(([t,u])=>`<a href="${u}"><span>${t}</span><small>Preberi vodič →</small></a>`).join('')}</div></section>`}
function productPage(lang){const l=locales[lang];let html=replaceI18n(sourceHtml,translations[lang]);html=html.replace('<html lang="sl">',`<html lang="${lang}">`).replace(/<title>[\s\S]*?<\/title>/,`<title>${esc(l.title)}</title>`).replace(/<meta name="description"[^>]*>/,`<meta name="description" content="${esc(l.description)}" />`).replace('</title>',`</title>${seoHead(lang)}`);if(lang==='sl')html=html.replace(/(<a[^>]*href="#order"[^>]*data-i18n="navOrder"[^>]*>)/,`<a href="/blog/" class="seo-blog-nav">Nasveti</a>$1`);html=html.replace(/<select id="languageSelect"[^>]*>/,`<select id="languageSelect" aria-label="Language" onchange="location.href=this.value==='sl'?'/' : '/'+this.value+'/'">`).replace(`<option value="${lang}">${lang.toUpperCase()}</option>`,`<option value="${lang}" selected>${lang.toUpperCase()}</option>`);if(lang==='sl')html=html.replace('<section class="faq section-pad">',`${blogCards()}<section class="faq section-pad">`);html=html.replace('<script src="/site-config.js"></script>',`<div id="priceBox" style="display:none!important"><span id="priceText"></span></div><script>localStorage.setItem('dust-lang','${lang}');</script><script src="/site-config.js"></script>`);html=html.replace('<script src="/app.js"></script>',`<script src="/app.js"></script><script>document.title=${JSON.stringify(l.title)};</script>`);return html}
function write(rel,content){const f=path.join(out,rel);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,content)}function copy(rel){const s=path.join(root,rel),d=path.join(out,rel);fs.mkdirSync(path.dirname(d),{recursive:true});fs.copyFileSync(s,d)}
for(const rel of ['styles.css','pricing.css','app.js','pricing.js','site-config.js','blog.css','favicon.svg','site.webmanifest'])if(fs.existsSync(path.join(root,rel)))copy(rel);fs.cpSync(path.join(root,'assets'),path.join(out,'assets'),{recursive:true});for(const lang of Object.keys(locales))write(lang==='sl'?'index.html':`${lang}/index.html`,productPage(lang));const blogUrls=buildBlog({root,out,base,abs,esc,write});const urls=['/','/en/','/de/','/es/',...blogUrls];write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u=>`  <url><loc>${abs(u)}</loc><lastmod>2026-08-08</lastmod></url>`).join('\n')}\n</urlset>`);write('robots.txt',`User-agent: *\nAllow: /\n\nSitemap: ${abs('/sitemap.xml')}\n`);console.log(`Built ${urls.length} indexable URLs for ${base}`);
